const data = {
  blog: {
    id: 1,
    name: 'Kent C. Dodds',
    description: 'Let’s make awesome with JavaScript (Photo by Luca Bravo on Unsplash)',
  },
  posts: [
    {
      id: 1,
      blogId: 1,
      authorId: 1,
      title: 'Prop Drilling',
      subTitle: 'What it is, why it’s good, why it’s bad, and how to avoid common problems with it.',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      date: 'May 21',
    },
    {
      id: 2,
      blogId: 1,
      authorId: 1,
      title: '💯 UPDATED: Advanced React Component Patterns ⚛️',
      subTitle: 'Now featuring the latest React APIs (like context) and entirely new patterns (like state reducer props).',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*ufuznjwWN4gP4S-jp2MOww.png',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*ufuznjwWN4gP4S-jp2MOww.png',
      date: 'Jun 1',
    },
    {
      id: 3,
      blogId: 1,
      authorId: 1,
      title: '✨ Free Frontend Masters Courses ⚛️ for a Week 🎉',
      subTitle: 'My Advanced Component Patterns and Testing React Applications are free on Frontend Masters for a limited time!',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      date: 'May 18',
    },

    {
      id: 4,
      blogId: 1,
      authorId: 1,
      title: 'When to use Control Props or State Reducers',
      subTitle: 'Comparing two similar patterns that enable many of the same use cases.',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: true,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*-rTkIBSzA1xVqPeuttf4kw.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*-rTkIBSzA1xVqPeuttf4kw.jpeg',
      date: 'Jun 11',
    },

    {
      id: 5,
      blogId: 1,
      authorId: 1,
      title: 'Prop Drilling',
      subTitle: 'What it is, why it’s good, why it’s bad, and how to avoid common problems with it.',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      date: 'May 21',
    },
    {
      id: 6,
      blogId: 1,
      authorId: 1,
      title: '💯 UPDATED: Advanced React Component Patterns ⚛️',
      subTitle: 'Now featuring the latest React APIs (like context) and entirely new patterns (like state reducer props).',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*ufuznjwWN4gP4S-jp2MOww.png',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*ufuznjwWN4gP4S-jp2MOww.png',
      date: 'Jun 1',
    },
    {
      id: 7,
      blogId: 1,
      authorId: 1,
      title: '✨ Free Frontend Masters Courses ⚛️ for a Week 🎉',
      subTitle: 'My Advanced Component Patterns and Testing React Applications are free on Frontend Masters for a limited time!',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      date: 'May 18',
    },

    {
      id: 8,
      blogId: 1,
      authorId: 1,
      title: 'Prop Drilling',
      subTitle: 'What it is, why it’s good, why it’s bad, and how to avoid common problems with it.',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*bWg9ZF6pzx0vddYqAnf5FA.jpeg',
      date: 'May 21',
    },
    {
      id: 9,
      blogId: 1,
      authorId: 1,
      title: '💯 UPDATED: Advanced React Component Patterns ⚛️',
      subTitle: 'Now featuring the latest React APIs (like context) and entirely new patterns (like state reducer props).',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*ufuznjwWN4gP4S-jp2MOww.png',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*ufuznjwWN4gP4S-jp2MOww.png',
      date: 'Jun 1',
    },
    {
      id: 10,
      blogId: 1,
      authorId: 1,
      title: '✨ Free Frontend Masters Courses ⚛️ for a Week 🎉',
      subTitle: 'My Advanced Component Patterns and Testing React Applications are free on Frontend Masters for a limited time!',
      contentMarkup: '<h1>post body markup</h1>',
      isLargePreview: false,
      previewImgUrl: 'https://cdn-images-1.medium.com/max/1000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      fullsizeImgUrl: 'https://cdn-images-1.medium.com/max/2000/1*iehP0UAWCqSzQ0CxhQcNrA.jpeg',
      date: 'May 18',
    },
  ],
  user: {
    id: 1,
    fullName: 'Kent C. Dodds',
    avatarUrl: 'https://cdn-images-1.medium.com/fit/c/120/120/1*9ZtET_L1852yXaDZJUo9CQ.png',
  },
};

export default data;
